version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-super-traders
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: super-traders-db
    ports:
      - '5432:5432'
    volumes:
      - super_traders_data:/var/lib/postgresql/data

volumes:
  super_traders_data:
